CENTER = [
    '',"AgACAgIAAxkBAAI-5mKWCI1GyhcqSi3k2BhNmyyriX4fAAJ5uzEbbo2wSI3uN413OGNbAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_D2KWCXesubtt-ZBSdkZ2qRInH5x9AAKDuzEbbo2wSOUaQT52TgmmAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_EWKWCZ6szCNaoiFWWTs-5i8apvGTAAKEuzEbbo2wSCTOi0lqYNY7AQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_E2KWCbFhjUFtviC2JS259VChdZEYAAKFuzEbbo2wSNpdQr_khFS1AQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_FWKWCdkpiU4oZQABf__0e1FxLjBObQACh7sxG26NsEhqY4vpoG_ZwQEAAwIAA3MAAyQE",
    "AgACAgIAAxkBAAI_F2KWCgqy1-48zcvF8ZO3m6NuUk33AAKJuzEbbo2wSJRqVldllIFDAQADAgADcwADJAQ",
    ]
RU = ['',
    "AgACAgIAAxkBAAI_KWKWCzvoKCB2yj7c0f3FBMZxDK5aAAKXuzEbbo2wSLubk1HREqr5AQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_K2KWC1ef9nm2s2jBRIc8DAraXRsNAAKYuzEbbo2wSCzbwSe8RjH4AQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_LWKWC2CU6lYxQ8X8z7sdsaAxNhhUAAKZuzEbbo2wSCujyAwZcNJNAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_L2KWC2qmEpocG7cF2hPz6QP00RISAAKauzEbbo2wSLze3RyjWtL8AQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_MWKWC3M6ZDlQGVLFm7hdGexiJs7NAAKbuzEbbo2wSC4v0kHx5Jv_AQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_M2KWC335rM7kUxxAx_H2BTjvGP3WAAKcuzEbbo2wSKOBoTH8flTPAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_NWKWC4UBJc6rwj3jQF-lCTveDcwcAAKduzEbbo2wSDGUsPtJmnSjAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_N2KWC45ipGbesU4y_b5RJNYPeJmTAAKWuzEbbo2wSPEF1kqUbWilAQADAgADcwADJAQ",
]
UZ = ['',
    "AgACAgIAAxkBAAI_GWKWCl66K8fDBnBrYivJhxN-sGgpAAKLuzEbbo2wSHLMH0sEJIPUAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_G2KWCqAFj5qnRkQjvfwgPIpyyjqJAAKPuzEbbo2wSBQZ0TrKi12wAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_HWKWCsSULM2yugwuyYdV6To8QR_GAAKRuzEbbo2wSB6VmeNPxlDUAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_H2KWCugnb92mpNv0Rf3b0jawp9R9AAKSuzEbbo2wSFi_oML19n9WAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_IWKWCv_MmwABu-WNJPlndJOcoJ6BmgACk7sxG26NsEif29EwHP3pdQEAAwIAA3MAAyQE",
    "AgACAgIAAxkBAAI_I2KWCw5tbpHySovr7m0XVlw8aHpyAAKUuzEbbo2wSP4IjXR-M9FIAQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_JWKWCxqFyFRo8iWI_Y59LP7wGAjwAAKVuzEbbo2wSBgq11AJ-Qw2AQADAgADcwADJAQ",
    "AgACAgIAAxkBAAI_J2KWCyc7_j6nVBkCF-quFPiqck8EAAKWuzEbbo2wSPEF1kqUbWilAQADAgADcwADJAQ",
]
OUR_COURCE = 'AgACAgIAAxkBAAI-2GKWB6knOL8nhPt1pZJG7yBdbnNqAAKAuzEbbo2wSNyN31ZI0pwBAQADAgADcwADJAQ'
ABOUT_US = 'AgACAgIAAxkBAAI-sWKWBw1bEJP8ySCwEVc1I8mbSJUeAAJ9uzEbbo2wSPMgJD3Ge8kUAQADAgADcwADJAQ'
CENTERS = 'AgACAgIAAxkBAAI-pWKWBnFVjt0QSTu9CKNXIuqSlXdnAAJ5uzEbbo2wSI3uN413OGNbAQADAgADcwADJAQ'